project:
  type: website
  output-dir: docs

website:
  title: "William's website"
  reader-mode: true
  repo-url: "https://github.com/WilliamXu233/qtm350-quiz02"
  navbar:
    pinned: true
    tools:
      - icon: github
        href: "https://github.com/WilliamXu233/qtm350-quiz02"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true


